services:
  postgres:
    image: postgres:16-alpine
    container_name: billetera-postgres
    environment:
      POSTGRES_DB: billetera_digital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema-docker.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - billetera-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: billetera-backend
    ports:
      - "8080:8080"
    environment:
      # Sobrescribe valores para docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/billetera_digital
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: clave-super-secreta-de-al-menos-256-bits-para-jwt-tokens-docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - billetera-network

volumes:
  postgres_data:
    driver: local

networks:
  billetera-network:
    driver: bridge
